spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopnow_products
    username: postgres
    password: S@ltyGuy!1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: shopnowsupersecretkey1234567890555555
  expiration: 11111  # 1 day in ms
server:
  port: 8082
