spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5433/shopnow_products
    username: lol
    password: lol
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: shopnowsupersecretkey1234567890555555
  expiration: 11111  # 1 day in ms
server:
  port: 8082
